# kitti_train.yaml

# =============================================================================
# General Training Settings
# =============================================================================
name: "SPACE_CLIP_KITTI_FULL"  # 실험에 맞게 이름 변경 (예: "Ablation_No_FiLM")
epochs: 10                     # 충분한 학습을 위해 에포크 수 증가 권장
learning_rate: 0.0001
weight_decay: 0.01
batch_size: 64                 # GPU 메모리에 맞게 조절
workers: 8
gpu: "0"
root: "."
checkpoint_path: ""

random_seed: 42
step_lr_step_size: 2
step_lr_gamma: 0.5 

# --- Logging & Validation Settings ---
validate_epochs: 1
num_log_images: 5
notes: "Full model training of Space-CLIP on KITTI." # 실험 내용에 맞게 수정
tags: "space_clip,kitti,full_model" # 실험 태그 수정


# =============================================================================
# Dataset Settings (KITTI - Eigen Split)
# =============================================================================
dataset: "kitti"
data_path: "./datasets/kitti_nyu/kitti/"
gt_path: "./datasets/kitti_nyu/kitti/train/"
filenames_file: "./train_test_inputs/kitti_eigen_train_files_with_gt.txt"

data_path_eval: "./datasets/kitti_nyu/kitti/"
gt_path_eval: "./datasets/kitti_nyu/kitti/val/"
filenames_file_eval: "./train_test_inputs/kitti_eigen_test_files_with_gt.txt"

input_height: 352
input_width: 704
clip_input_size: 224

do_random_rotate: true
degree: 1.0

min_depth: 0.001
max_depth: 80
min_depth_eval: 0.001
max_depth_eval: 80
eigen_crop: true
garg_crop: false


# =============================================================================
# SPACE-CLIP Model Specific Settings
# =============================================================================
# [수정] 새로운 아키텍처를 위한 설정
use_film: true                     # FiLM 사용 여부
use_structural_pathway: true       # True: 구조적 정제 경로 사용, False: 사용 안 함

# --- CLIP Backbone Settings ---
clip_model_name: "openai/clip-vit-base-patch16"
freeze_clip_vision: true

# --- Pathway Feature Indices ---
# 메인 경로: 깊은 레이어부터 (의미론적 정보)
main_path_indices: [12, 9, 6, 3] 
# 구조적 경로: 초기 레이어부터 (구조적 정보)
structural_path_indices: [2, 1, 0]

# --- FiLM Module Settings (if use_film is true) ---
film_param_hidden_dim: 256

# --- Decoder Architecture Settings ---
# 디코더 각 단계의 채널 수. main_path_indices와 길이가 같아야 함.
decoder_channels: [256, 128, 64, 32] 
decoder_dropout: 0.1

w_ssim: 0.5